name: Formats

on: ['push', 'pull_request']

jobs:
  formats:
    runs-on: ubuntu-latest
    name: Lint and types

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, mbstring, zip
          coverage: none

      - run: composer update --prefer-stable --no-interaction --prefer-dist

      - run: composer test:lint

      - run: composer test:types
